import {FormEvent,useEffect,useState} from 'react';
import axios from 'axios';
import {notificationsApi,type ChannelInput,type RuleInput} from '../api/notifications';
import type {NotificationChannel,NotificationChannelType,NotificationRule,NotificationTrigger} from '../types';

const TYPES:NotificationChannelType[]=['EMAIL','MATTERMOST','WEBHOOK'];
const TYPE_LABEL:Record<NotificationChannelType,string>={EMAIL:'Email',MATTERMOST:'Mattermost',WEBHOOK:'Custom webhook'};
const TRIGGERS:NotificationTrigger[]=['NEW_DISCUSSION','NEW_COMMENT','NEW_REPLY','FIRST_VOTE','NEW_REACTION','STATUS_CHANGED','JIRA_ACTION_CREATED','MENTION'];
const TRIGGER_LABEL:Record<NotificationTrigger,string>={NEW_DISCUSSION:'Новое обсуждение',NEW_COMMENT:'Новый комментарий',NEW_REPLY:'Ответ на комментарий',FIRST_VOTE:'Первый голос',NEW_REACTION:'Новая реакция',STATUS_CHANGED:'Изменение статуса',JIRA_ACTION_CREATED:'Создание задачи Jira',MENTION:'Упоминание'};
const emptyForm:ChannelInput={name:'',type:'EMAIL',url:'',secret:''};

function message(error:unknown){if(axios.isAxiosError(error)){const data=error.response?.data as {message?:string;detail?:string}|undefined;return data?.message||data?.detail||'Сервер не смог выполнить запрос.'}return 'Не удалось выполнить запрос.'}
function date(value:string|null){return value?new Intl.DateTimeFormat('ru',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Ещё не проверялось'}

export default function NotificationSettingsPage(){
  const [channels,setChannels]=useState<NotificationChannel[]>([]),[rules,setRules]=useState<NotificationRule[]>([]);
  const [form,setForm]=useState<ChannelInput>(emptyForm),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [editing,setEditing]=useState<number|null>(null),[replacement,setReplacement]=useState<Record<number,{url:string;secret:string}>>({});
  const load=()=>{setLoading(true);setError('');Promise.all([notificationsApi.channels(),notificationsApi.rules()]).then(([c,r])=>{setChannels(c);setRules(r)}).catch(e=>setError(message(e))).finally(()=>setLoading(false))};
  useEffect(load,[]);
  const run=async(key:string,action:()=>Promise<unknown>,success:string)=>{setBusy(key);setError('');setNotice('');try{await action();setNotice(success);await Promise.all([notificationsApi.channels().then(setChannels),notificationsApi.rules().then(setRules)]);return true}catch(e){setError(message(e));return false}finally{setBusy('')}};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!form.name.trim()){setError('Укажите название подключения.');return}if(form.type!=='EMAIL'&&!/^https:\/\/\S+$/.test(form.url||'')){setError('Укажите абсолютный HTTPS URL.');return}if(form.type==='WEBHOOK'&&!form.secret){setError('Для custom webhook укажите секрет.');return}if(await run('create',()=>notificationsApi.createChannel(form),'Подключение добавлено.'))setForm(emptyForm)};
  const updateName=(channel:NotificationChannel,name:string)=>{if(!name.trim()){setError('Название не может быть пустым.');return}run(`save-${channel.id}`,()=>notificationsApi.updateChannel(channel.id,{name,type:channel.type,active:channel.active,url:'',secret:''}),'Настройки сохранены.')};
  const replace=(channel:NotificationChannel)=>{const values=replacement[channel.id]||{url:'',secret:''};if(values.url&&!/^https:\/\/\S+$/.test(values.url)){setError('Укажите абсолютный HTTPS URL.');return}if(!window.confirm('Заменить сохранённые реквизиты подключения?'))return;run(`replace-${channel.id}`,()=>notificationsApi.updateChannel(channel.id,{name:channel.name,type:channel.type,active:channel.active,...values}),'Реквизиты заменены.').then(()=>{setReplacement(v=>({...v,[channel.id]:{url:'',secret:''}}));setEditing(null)})};
  const changeRule=(trigger:NotificationTrigger,channel:NotificationChannel,value:string)=>{const rule=rules.find(r=>r.trigger===trigger&&r.channelId===channel.id&&r.scope==='ALL_DISCUSSIONS');const input:RuleInput={trigger,channelId:channel.id,scope:'ALL_DISCUSSIONS',discussionId:null,active:value==='on'};if(value==='off'&&rule)return run(`rule-${trigger}-${channel.id}`,()=>notificationsApi.deleteRule(rule.id),'Правило отключено.');if(rule)return run(`rule-${trigger}-${channel.id}`,()=>notificationsApi.updateRule(rule.id,input),value==='on'?'Правило включено.':'Правило приостановлено.');return run(`rule-${trigger}-${channel.id}`,()=>notificationsApi.createRule(input),'Правило включено.')};

  return <main className="notification-page">
    <div className="notification-heading"><div><span className="eyebrow">ЛИЧНЫЕ НАСТРОЙКИ</span><h1>Настройки уведомлений</h1><p>Подключите способы доставки и выберите события, о которых хотите знать.</p></div></div>
    {error&&<div className="notification-alert error" role="alert">{error} <button type="button" onClick={()=>setError('')} aria-label="Закрыть сообщение">×</button></div>}
    {notice&&<div className="notification-alert success" role="status">{notice}</div>}
    {loading?<div className="state" aria-live="polite">Загрузка настроек…</div>:<>
      <section className="settings-section" aria-labelledby="connections-title"><div className="section-title"><div><h2 id="connections-title">Подключения</h2><p>Секретные значения никогда не отображаются после сохранения.</p></div><span className="count-badge">{channels.length}</span></div>
        {channels.length===0?<div className="empty-settings"><b>Подключений пока нет</b><span>Добавьте email, Mattermost или webhook ниже.</span></div>:<div className="channel-list">{channels.map(channel=><article className="channel-card" key={channel.id}>
          <div className="channel-card-head"><div><span className="channel-type">{TYPE_LABEL[channel.type]}</span><h3>{channel.name}</h3></div><span className={`channel-state ${channel.active?'enabled':'disabled'}`}>{channel.active?'Активно':'Отключено'}</span></div>
          <dl><div><dt>Подключение</dt><dd><code>{channel.connection||'Скрыто ••••••••'}</code></dd></div><div><dt>Последняя успешная проверка</dt><dd>{date(channel.lastSuccessfulCheckAt)}</dd></div></dl>
          <div className="channel-actions"><button className="secondary" disabled={!!busy||!channel.active} onClick={()=>run(`test-${channel.id}`,()=>notificationsApi.testChannel(channel.id),'Проверка успешно отправлена.')}>Проверить подключение</button><button className="link-button" onClick={()=>setEditing(editing===channel.id?null:channel.id)}>{editing===channel.id?'Отмена':'Изменить'}</button>{channel.active?<button className="link-button" onClick={()=>window.confirm('Отключить этот канал?')&&run(`disable-${channel.id}`,()=>notificationsApi.disableChannel(channel.id),'Канал отключён.')}>Отключить</button>:<button className="link-button" onClick={()=>run(`enable-${channel.id}`,()=>notificationsApi.updateChannel(channel.id,{name:channel.name,type:channel.type,active:true,url:'',secret:''}),'Канал включён.')}>Включить</button>}<button className="link-button danger" onClick={()=>window.confirm('Удалить канал и все связанные правила? Это действие нельзя отменить.')&&run(`delete-${channel.id}`,()=>notificationsApi.deleteChannel(channel.id),'Канал удалён.')}>Удалить</button></div>
          {editing===channel.id&&<fieldset className="edit-channel"><legend>Изменение подключения</legend><label>Пользовательское название<input defaultValue={channel.name} onBlur={e=>e.target.value!==channel.name&&updateName(channel,e.target.value)}/></label>{channel.type!=='EMAIL'&&<><p className="secret-note">Сейчас сохранено: <code>{channel.connection||'••••••••'}</code>. Оставьте поля пустыми, если не хотите заменять реквизиты.</p><label>Новый HTTPS URL<input type="url" placeholder="https://…" value={replacement[channel.id]?.url||''} onChange={e=>setReplacement(v=>({...v,[channel.id]:{url:e.target.value,secret:v[channel.id]?.secret||''}}))}/></label>{channel.type==='WEBHOOK'&&<label>Новый секрет<input type="password" autoComplete="new-password" value={replacement[channel.id]?.secret||''} onChange={e=>setReplacement(v=>({...v,[channel.id]:{url:v[channel.id]?.url||'',secret:e.target.value}}))}/></label>}<button className="secondary" type="button" disabled={!!busy||(!replacement[channel.id]?.url&&!replacement[channel.id]?.secret)} onClick={()=>replace(channel)}>Заменить реквизиты</button></>}</fieldset>}
        </article>)}</div>}
      </section>

      <section className="settings-section" aria-labelledby="add-channel-title"><h2 id="add-channel-title">Добавить подключение</h2><form className="channel-form" onSubmit={submit} noValidate><fieldset><legend className="visually-hidden">Параметры нового подключения</legend><label>Тип<select value={form.type} onChange={e=>setForm({...emptyForm,type:e.target.value as NotificationChannelType})}>{TYPES.map(type=><option key={type} value={type}>{TYPE_LABEL[type]}</option>)}</select></label><label>Пользовательское название<input value={form.name} maxLength={100} onChange={e=>setForm({...form,name:e.target.value})} placeholder={form.type==='EMAIL'?'Основная почта':'Рабочие уведомления'} required/></label>{form.type==='EMAIL'?<div className="email-hint"><b>Подтверждённый адрес аккаунта</b><span>Уведомления будут приходить на подтверждённый email текущего аккаунта.</span></div>:<label>HTTPS URL<input type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://hooks.example.com/…" required/></label>}{form.type==='WEBHOOK'&&<label>Секрет для подписи<input type="password" autoComplete="new-password" value={form.secret} onChange={e=>setForm({...form,secret:e.target.value})} required/><small>Используется для HMAC-SHA256 подписи запросов.</small></label>}<button className="primary" disabled={!!busy}>{busy==='create'?'Сохранение…':'Добавить подключение'}</button></fieldset></form></section>

      <section className="settings-section rules-section" aria-labelledby="rules-title"><div className="section-title"><div><h2 id="rules-title">Какие уведомления отправлять</h2><p>Для каждого события можно выбрать сразу несколько каналов или временно приостановить правило.</p></div></div>{channels.length===0?<div className="empty-settings">Сначала добавьте хотя бы одно подключение.</div>:<div className="rules-scroll"><table className="rules-table"><caption className="visually-hidden">Матрица событий и каналов уведомлений</caption><thead><tr><th scope="col">Событие</th>{channels.map(c=><th scope="col" key={c.id}>{c.name}<small>{TYPE_LABEL[c.type]}</small></th>)}</tr></thead><tbody>{TRIGGERS.map(trigger=><tr key={trigger}><th scope="row">{TRIGGER_LABEL[trigger]}</th>{channels.map(channel=>{const rule=rules.find(r=>r.trigger===trigger&&r.channelId===channel.id&&r.scope==='ALL_DISCUSSIONS');return <td key={channel.id}><label className="visually-hidden" htmlFor={`${trigger}-${channel.id}`}>{TRIGGER_LABEL[trigger]} — {channel.name}</label><select id={`${trigger}-${channel.id}`} value={!rule?'off':rule.active?'on':'paused'} disabled={!!busy||!channel.active} onChange={e=>changeRule(trigger,channel,e.target.value)}><option value="off">Выкл.</option><option value="on">Вкл.</option><option value="paused">Пауза</option></select></td>})}</tr>)}</tbody></table></div>}</section>
    </>}
  </main>
}
